In [2]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings ('ignore')

In [8]:
fj=pd.read_csv(r"C:\Users\arjun\Downloads\fake_job_postings.csv.xls")

In [9]:
fj.shape

(17880, 35)

In [13]:
fj.columns

Index(['job_id', 'title', 'location', 'department', 'salary_range',
       'company_profile', 'description', 'requirements', 'benefits',
       'telecommuting', 'has_company_logo', 'has_questions', 'employment_type',
       'required_experience', 'required_education', 'industry', 'function',
       'fraudulent', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
       'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24',
       'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28',
       'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32',
       'Unnamed: 33', 'Unnamed: 34'],
      dtype='object')

In [18]:
fj['X']=fj['company_profile'].apply(str)+ "  " +fj['salary_range'].apply(str)+ "  " +fj['description'].apply(str)+ "  " +fj['requirements'].apply(str)   + "  " +fj[ 'benefits'].apply(str) + "  " +fj['description'].apply(str)    + "  " +fj['industry'].apply(str)                                                                                            

In [19]:
fj=fj.rename(columns={'fraudulent':'Y'})

In [20]:
df = fj.loc[:,['X','Y']]

In [21]:
df.head(2)

,X,Y
0,"We're Food52, and we've created a groundbreaki...",0
1,"90 Seconds, the worlds Cloud Video Production ...",0


In [22]:
import nltk

In [23]:
from nltk.corpus import stopwords

In [24]:
l1=stopwords.words('english')
l1

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [25]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [26]:
def text_process(mess):
    """
    1.remove the punctuatiom
    2.remove the stopwords
    3.return the list of clean textwords

    """
    nopunc=[char for char in mess if char not in string.punctuation]
    nopunc="".join(nopunc)
    return [word for word in nopunc.split() if word not in l1]

In [27]:
from sklearn.feature_extraction.text import CountVectorizer
# assign a Id/ token number to each word)

In [28]:
bow_transformer =  CountVectorizer(analyzer = text_process).fit(fj['X'])

In [29]:
len(bow_transformer.vocabulary_)

190729

In [ ]:
# tdm -----> term document matrix

In [31]:
tdm = bow_transformer.transform(fj['X'])

In [32]:
tdm.shape

(17880, 190729)

In [33]:
type(tdm)
# tdm will be our X used in model building

scipy.sparse._csr.csr_matrix

In [34]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y,test_y = train_test_split(tdm,fj.Y)

In [35]:
from sklearn.metrics import *

In [36]:
from sklearn.linear_model import LogisticRegression
logrig=LogisticRegression()
logrig.fit(train_x,train_y)
pred = logrig.predict(test_x)
print(confusion_matrix(test_y,pred))
print(classification_report(test_y,pred))

[[4230   16]
 [  68  156]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      4246
           1       0.91      0.70      0.79       224

    accuracy                           0.98      4470
   macro avg       0.95      0.85      0.89      4470
weighted avg       0.98      0.98      0.98      4470



In [37]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(train_x, train_y)
pred = dt.predict(test_x)
tab = confusion_matrix(test_y, pred)
print(tab)
print(classification_report(test_y, pred))

[[4228   18]
 [  61  163]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      4246
           1       0.90      0.73      0.80       224

    accuracy                           0.98      4470
   macro avg       0.94      0.86      0.90      4470
weighted avg       0.98      0.98      0.98      4470



In [38]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(train_x,train_y)
pred = rf.predict(test_x)
tab = confusion_matrix(test_y, pred)
print(tab)
print(classification_report(test_y, pred))

[[4246    0]
 [  74  150]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      4246
           1       1.00      0.67      0.80       224

    accuracy                           0.98      4470
   macro avg       0.99      0.83      0.90      4470
weighted avg       0.98      0.98      0.98      4470



In [ ]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer # function

In [ ]:
sent=SentimentIntensityAnalyzer()

In [ ]:
score_list=[]
for i in range(0,fj.shape[0]):
    score=sent.polarity_scores(fj(